version: "3"
services:
  db:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
  redis:
    image: "redis:alpine"
    container_name: "leaderboard-redis"
    ports:
      - 6379:6379
    volumes:
      - db-data:/data/leaderboard
  api:
    image: "mmirajkar/pomo-api"
    container_name: "pomo-api"
    ports:
      - 3000:3000

  web:
    image: "mmirajkar/pomo-frontend"
    build: ./src
    container_name: "pomo-frontend"
    ports:
      - "8080:8080"

volumes:
  db-data:
