version: "3"
services:
  db:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
  redis:
    image: "redis:alpine"
    container_name: "leaderboard-redis"
    ports:
      - 6379:6379
    volumes:
      - db-data:/data/leaderboard

volumes:
  db-data:
