version: "3"
services:
  db:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'sqlserver'
    ports:
      - 27017:27017
    environment: 
      MSSQL_SA_PASSWORD: 'secret'
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/data/db
  redis:
    image: 'redis:alpine'
    container_name: 'leaderboard-redis'
    ports:
      - 6379:6379
    volumes:
      - db-data:/data/leaderboard

volumes:
  db-data: